<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'staticanalysis/parsers/xhpast/api/exception');
phutil_require_module('arcanist', 'staticanalysis/parsers/xhpast/api/node');
phutil_require_module('arcanist', 'staticanalysis/parsers/xhpast/api/token');
phutil_require_module('arcanist', 'staticanalysis/parsers/xhpast/bin');

phutil_require_module('phutil', 'utils');


phutil_require_source('XHPASTTree.php');
