<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'workflow/base');

phutil_require_module('phutil', 'console');


phutil_require_source('ArcanistTasksWorkflow.php');
