<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'lint/linter/base/test');
phutil_require_module('arcanist', 'lint/linter/spelling');
phutil_require_module('arcanist', 'workingcopyidentity');


phutil_require_source('ArcanistSpellingLinterTestCase.php');
