<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'lint/linter/base');
phutil_require_module('arcanist', 'lint/severity');

phutil_require_source('ArcanistSpellingLinter.php');
phutil_require_source('ArcanistSpellingDefaultData.php');
