<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'lint/severity');

phutil_require_module('phutil', 'console');
phutil_require_module('phutil', 'utils');


phutil_require_source('ArcanistLintRenderer.php');
phutil_require_source('ArcanistLintSummaryRenderer.php');
phutil_require_source('ArcanistLintJSONRenderer.php');
