<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'lint/linter/base');
phutil_require_module('arcanist', 'lint/severity');
phutil_require_module('arcanist', 'staticanalysis/parsers/xhpast/api/tree');
phutil_require_module('arcanist', 'staticanalysis/parsers/xhpast/bin');

phutil_require_module('phutil', 'utils');


phutil_require_source('ArcanistXHPASTLinter.php');
