<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'difference');
phutil_require_module('arcanist', 'unit/engine/phutil/testcase/exception');
phutil_require_module('arcanist', 'unit/result');

phutil_require_module('phutil', 'readableserializer');
phutil_require_module('phutil', 'utils');


phutil_require_source('ArcanistPhutilTestCase.php');
