<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'differential/commitmessage');

phutil_require_module('phutil', 'console');
phutil_require_module('phutil', 'utils');


phutil_require_source('BranchInfo.php');
