<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'parser/diff/change');
phutil_require_module('arcanist', 'parser/diff/changetype');
phutil_require_module('arcanist', 'parser/diff/hunk');
phutil_require_module('arcanist', 'repository/api/base');

phutil_require_module('phutil', 'utils');


phutil_require_source('ArcanistDiffParser.php');
