<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'repository/api/base');

phutil_require_module('phutil', 'future/exec');
phutil_require_module('phutil', 'utils');


phutil_require_source('ArcanistGitAPI.php');
