<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'exception/usage');


phutil_require_source('ArcanistNoEffectException.php');
