<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'parser/commentremover');
phutil_require_module('arcanist', 'unit/engine/phutil/testcase');


phutil_require_source('ArcanistCommentRemoverTestCase.php');
