<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'repository/api/base');


phutil_require_source('ArcanistMercurialParser.php');
