<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */




phutil_require_source('ArcanistDifferentialCommitMessage.php');
phutil_require_source('ArcanistDifferentialCommitMessageParserException.php');
